### ISSUE TITLE
🐞 [Bug]: The resource filters are not functioning as expected.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-go#1052]
### What happened?

I've been requested to filter the nodes with dome queries, the queries include the `SSD` unit, which was `15`, and the result returned included the `node 11`, while the `node 11` has around `26 GB`, so what is the probe here??

```ts
const totalResources = 512110190592
const totalResourcesSru = 512110190592
const usedResourcesSru = 484182065152
const diff = totalResourcesSru - usedResourcesSru
diff / 1024 / 1024 / 1024
26.010093688964844
```

Could be related to https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2750

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/06f0af28-9b18-4758-a467-5c60437d6bad)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8fe1fcdb-8b92-4240-a9db-67cdb03b8667)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/520ecc2f-15ac-4c38-90c6-1d9c1c0d84e3)

### which network/s did you face the problem on?

Dev

### Twin ID/s

143

### Relevant log output

```console
N/A
```

**Comment by Omarabdul3ziz** [comment]
here what i found:
- if we considered the node stats as the truth point, it looks the total/used reported capacity in the node response is slimier to its capacity so no problem on the node capacity reporting.
- also no problem in the filters, for example. node 11 have `total_sru=512110190592` and `used_sru=480436551680` so it should have free `31673638912` and that is the case https://gridproxy.dev.grid.tf/nodes?free_sru=31673638912 returns node 11
- tracing the raised error from zos `not enough space left in pools of this type ssd`. it is the way zos spliting the ssd to pools so requesting 29gb will not cover the pool check `zos.storage.pools`

since it is not an issue on the proxy, i opened an issue on zos to investigate further.  
- https://github.com/threefoldtech/zos/issues/2351
