### ISSUE TITLE
Add alphanumeric validation  naming for any deployment name, disk name, and network name with a minimum and maximum length.

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-go#1055]
### Is your feature request related to a problem? Please describe

Yes, in the ts sdk the following [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2364) 

### Describe the solution you'd like

Add alphanumeric validation  naming for any deployment name, disk name, and network name with a minimum and maximum length.

**Comment by rawdaGastan** [comment]
I think your validations are restricted somehow because the objects are already deployed, so they are valid. Also, deployment names can have underscores

**Comment by Omarabdul3ziz** [comment]
now deployment names have a validation to be any char/number/_ with max length 50char. 

but when i tried to test a deployment with name 39char, i got this error 
![image](https://github.com/user-attachments/assets/ebd233c8-8046-48e7-a1de-b00600de2abb)

tracking the error it comes from `cloud-hypervisor` it can't start a machine due to limitations on the `--fs` flag tag param
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/92e48f7cf6b3b5b5abfe645f91553f3cb9fb0c92/virtio-devices/src/vhost_user/fs.rs#L46

could we follow this limitation instead? at least for the VM workloads.

**Comment by Omarabdul3ziz** [comment]
all good thanks
