### ISSUE TITLE
dependency conflict in `go-subkey` versions

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#1290]
some packages using `go-subkey` and other uses `go-subkey/v2` this leads to error in building happen on `tfchain-client-go@77e684bcb1b2` and `rmb-sdk-go@v0.16.0`

![image](https://github.com/user-attachments/assets/8c0347d8-3e2a-4cd3-a8f4-0fcbf51dc5c8)

to reproduce
- a simple rmb call script that imports the two packages
- replace the packages with local pkgs
- also replace the tfchain in sdk-rmb to use local chain client
- tidy all and run the script

**Comment by sameh-farouk** [comment]
**Update:**
This issue is caused locally by running `go get -u` or a similar command, which updated the `subkey` package from `1.0.3` to `1.0.4`. Although it's a patch increment, this version introduces major, incompatible API changes.
Reverting the version in the local mod file should resolve the issue.

**Comment by Omarabdul3ziz** [comment]
verified, editing the subkey dep to use `1.0.3` works fine
