### ISSUE TITLE
node gpu info indexer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#209]
suggesting to have a background worker that calls listGPUs on all of the nodes and insert them in the db, full gpus info per node maybe should be available on `/nodes/<nodeid>/gpus`

**Comment by xmonader** [comment]
This also means we can expand the filters by gpu device type as well by searching for devices too along with `has_gpu` feature

**Comment by alichaddad** [comment]
The indexer will run periodically and query all the available nodes, it will then retrieve the GPU information for each node if available and store it in a new table, the fields of that table would be:

- `id` gpu id
- `node_id` the id of the node
- `vendor` GPU vendor name
- `device` GPU device name
- `contract`


While we could store the device and vendor id as well for simplifying querying, it seems a bit redundant and we can still use the id to query via device/vendor id if needed.

Listing nodes now will allow filtering based on device and gpu partial names and if there is a need to list to list available GPU vendors/devices a new endpoint can be added to retrieve that information from the new `node_gpu` table.

**Comment by muhamadazmy** [comment]
I think it's important to also store the Vendor ID and the Device ID (numeric values) that are part of the ID. Later to search for a specific device, the user can search the full PCI database for a specific device name, then we use that (numeric) ID to search the database.

> IMHO the device and vendor names are the redundant data not the other way around

If you also going to store the device and vendor names, it's important to also keep the numeric ids. 

I would also drop the contract from the database, since this is useless during the search and is useful only to someone who has the node rented, hence can then get in real time from the node directly. the contract can be out of date as well.

A free node for renting can only has all contract ids values as zeros.

**Comment by muhamadazmy** [comment]
As @alichaddad brought my attention that the device/vendor ids are already in the ID of the device we can then not store the numeric values but then we can do partial string matches on the ID to match on specific vendor and or device with their ids

**Comment by Mahmoud-Emad** [comment]
Hey @alichaddad 
What is the status here?

**Comment by alichaddad** [comment]
Code is ready for review should be done maximum tomorrow

**Comment by alichaddad** [comment]
PR review is still in progress

**Comment by A-Harby** [comment]
Verified,

Proxy calls are added and works successfully, and docs are updated.
https://gridproxy.dev.grid.tf/nodes?gpu_vendor_name=Advanced%20Micro%20Devices
https://gridproxy.dev.grid.tf/nodes?gpu_device_name=Navi%2031
https://gridproxy.dev.grid.tf/nodes?gpu_available=true
https://gridproxy.dev.grid.tf/nodes?has_gpu=true
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/be1b45ca-f840-47e6-888e-3693a2c10a4b)


Indexer couldn't be verified but it will be verified once a new GPU card added.
