### ISSUE TITLE
Repeating error messages from relay client in proxy

### ISSUE THREAD

**Issue by alichaddad** [threefoldtech/tfgrid-sdk-go#262]
## Describe the bug

After deploying grid proxy to dev environment the following error message keeps on being produced. This behavior couldn't be replicated locally.

## To Reproduce

  Deploy grid proxy on dev. Or check the current deployment.

## Screenshots

<img width="1359" alt="logs" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/24762033/cde6d877-ff6e-414b-ba3a-5a457d30424f">

**Comment by xmonader** [comment]
any insights on this?

**Comment by sameh-farouk** [comment]
Most likely a flaky connection?
It seems that Relay has an issue with unstable connections. I have opened this [issue](https://github.com/threefoldtech/rmb-rs/issues/146) to track it.

As for Gridproxy, I have checked the fresh logs and found no more repeatedly errors similar to what OP mentioned. Gridproxy also seems to be working fine on development and QA networks and AFAIK, no problems was reported since this issue was created.

Do you think we need to investigate further, @xmonader?

**Comment by xmonader** [comment]
No need for more investigations indeed, I'll close as can't reproduce
