### ISSUE TITLE
Some unit records couldn't parsed using ParseUint

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-go#306]
## Describe the bug

From Gridproxy logs on dev network

```bash
error couldn't parse total_sru strconv.ParseUint: parsing "512067475865.6": invalid syntax: bad request
error couldn't parse total_cru strconv.ParseUint: parsing "44.54": invalid syntax: bad request
```

**Comment by Omarabdul3ziz** [comment]
the issue happened because of a bad request from the client. we are handling all the numeric value filters as `uint64` so passing a float value to `total_sru`, `total_cru`, or ... will raise an error. 

but anyway we are heading to use the `scheme` package to handle all the query params. linked the issue to the scheme pr


this part is removed in the mentioned pr
https://github.com/threefoldtech/tfgrid-sdk-go/blob/cca933e1bf26694bff86e85da61bfe973ad3c0be/grid-proxy/internal/explorer/helpers.go#L96-L99
