### ISSUE TITLE
separate bill reports from contracts query

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#347]
each contract has a bill report reported every hour, hence a single contract could have thousands of bill reports. 
so, if there is no actual benefit for a user to have the contract bill reports aggregated within the contract's information, we should then separate the bill reports from the contracts information.

**Comment by muhamadazmy** [comment]
There is no clear explanation of what this issue is trying to solve. What is problematic now that this issue is trying to solve. This is a normal one to many relation. 

In the database this can very easily implemented as two tables, with a foreign key in the bill table. And definitely can't be embedded in the contract object.

The question is, since we will have a report for each hour per contract, the bills table can get too big eventually. Can we instead do:
- Retention: Move older bills to archive and only keep a 3 month worse of bills per contract
- Aggregation: Aggregate older bills into one bill. and only keep 3 month worse of bills per contract
- Deletion?: just delete old bills of older than 3 month


Either this or that, depends on the use case and what we need to do

**Comment by Omarabdul3ziz** [comment]
update: 
pr is ready for review

**Comment by Omarabdul3ziz** [comment]
update: 
merged now but waiting for a release to move to verification

**Comment by A-Harby** [comment]
Verified, Devnet.

Two new endpoints were added to the contract: `/contracts/contract_id` and `/contracts/contract_id/bills`.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/8219a62a-ecea-441d-b179-e41622f4418a)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/21303647-5975-47fe-b5a3-3891dbbc4d1a)

[Swagger](https://gridproxy.dev.grid.tf/swagger/index.html#/Contract) and [Docs](https://github.com/threefoldtech/tfgrid-sdk-go/blob/ac6592e8a210a4a98b1349909a331ee10c71b6d9/grid-proxy/docs/docs.go#L135C11-L135C19) were updated.
