### ISSUE TITLE
integration tests fails (grid-client)

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#441]
- fix nightly workflow for grid-client
- add a mnemonic for the repo for all networks

**Comment by xmonader** [comment]
@Eslam-Nawara what is the progress here?

**Comment by Eslam-Nawara** [comment]
@xmonader 
- the accounts used in integration tests needs to be funded and rawda is working on it
- some of the tests fails due to nodes don't respond and the connection times out
- there's no enough resources on devnet to run some tests

**Comment by Eslam-Nawara** [comment]
WIP: 
- updated all the tests to return if any assertion failed 
- updated the tests to not update the existing node filter and use a copy of it instead
- rename all networks in tests to stop old conflicts

**Comment by Eslam-Nawara** [comment]
WIP: 
All failing tests now, fails with context deadline exceeded messages even after increasing the context time and the nodes are actually up and reachable
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/35cba4f2-f86c-492c-abcf-5bb6e6f397d6)

**Comment by Eslam-Nawara** [comment]
WIP: 
- Used a random string generator to stop the error `global workload with the same name exists: conflict`
- Set test timeout in the nightly workflow to 30 min as it was the default 10 and not all the tests had chance to finish 

Problems:
- Some tests have the same behavior as the last comment, nodes are up and reachable but the requests timeout when sent to them
- BatchVm test fails due to ssh connection refused, sounds like ygg problem

**Comment by rawdaGastan** [comment]
All green ✅ 

- https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/8251316421
