### ISSUE TITLE
Devnet: node workload details fail to load

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-go#505]
### Description

Loading node workload details on devnet dashboard fails

### Steps to reproduce
1. https://dashboard.dev.grid.tf/explorer/nodes
2. click a node -> no workload details

### Logs/Alerts

Gridproxy node details time out: https://gridproxy.dev.grid.tf/nodes/14/statistics
![image_2023-11-20_10-43-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/a6cc4abb-1b96-4957-b561-03a65509f5ad)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/c86d7697-2ff4-442d-88f9-f59fd405496f)

Same service versions running on a devnet stack separate from k8s, which works fine: https://dashboard.bknd1.dev.ava.tf/explorer/nodes

**Comment by Omarabdul3ziz** [comment]
update: wip
- to reproduce the issue locally run proxy at the version deployed on devnet against dump dev db. but things work fine.
- a restart for the gridproxy service on the dev cluster. and the endpoint is working again.
- similar issue reported before. https://github.com/threefoldtech/tfgrid-sdk-go/issues/104
- investigating what makes the connection didn't recover in the first place but the code looks fine.
- from the gridproxy logs noticed the context fails for different reasons, `canceled` and `timeout`
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/f67a9335-b63d-4caa-8fa3-afd45d55c92d)
- also noticed the logs on the relay pod not only related to the calls from the proxy, it is still happens after the proxy restart even things works fine.
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/5bef2e52-710c-4563-8379-d2c1d13d2ac5)

**Comment by Omarabdul3ziz** [comment]
update:
was debugging with @AbdelrahmanElawady, we explored more in the code but found nothing suspicious. also, the issue can't reproduced locally.  noted these while debugging
- the main issue happens because the request exceeds the deadline for the handler`30 sec` without responses 
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/b0b9a610-6c4e-43af-a89d-e9901eccff2b)
 
- but looking at the nodes logs it actually receive the request and push the response 
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/5726e494-f6d7-4a66-813c-1d75385dfba9)

- The issue happened again on dev net and some connections in `TIME_WAIT` state 
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/387a7747-78ff-43f5-a3bf-7b302feffa77)
- some yggdrasil logs on the dev nodes timedout
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/57d52b26-7108-49c1-94e8-720254e19a24)

**Comment by Omarabdul3ziz** [comment]
We continued debugging on this and ..

update:

- Azmy found out that the issue was using the same identity for two gridproxy instances, each trying to connect to a different relay. so they keep updating the relay in the same twin object.
- things are good now, the proxy twin object uses the dev relay https://gridproxy.dev.grid.tf/twins?twin_id=3 and works fine https://gridproxy.dev.grid.tf/nodes/11/statistics

noted while debugging * may be helpful in future debugging for similar issues *:

- peer reconnecting for failed connections works fine 
  tracking the connections in gridproxy discovered there this three opened connections to the dev cluster.
  one for the relay from the main server, another for the relay from the GPU indexer, and a mysterious third one.
  but after tracking it appears to be a connection to the chain while the start of the RPC client to get the twin identity.
    
  tried to kill the nodes to discover that only two connections were reconnecting if closed not the third one which was expected to be needed only on the RPC client initialization so no need to reconnect it.
    
- multiple connections with the relay.
  if it happens and connects to the relay with the same twinID and sessionID. the relay will use the latest one and drop the other. which will try to reconnect again and become the latest connection and so on... 
  
  hence you may get an error `websocket: close 1006 (abnormal closure) unexpected EOF`
    
  the two relay connections in the proxy have different session id to they safely live together

**Comment by Omarabdul3ziz** [comment]
all works fine now and nothing further needs to be done. moves to verification
