### ISSUE TITLE
🐞 [Bug]: [mainnet] inconsistency between nodes has_gpu filter and nodes non_gpu field 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-go#636]
### What happened?

version : 2.2.0
could not get gpus on mainnet all nodes are with 0 gpu in the dashboard

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/44776512-cffa-4157-850b-77df64fb6649)

after investigation using the gridproxy
when using <node_id>/gpu  :

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/03cfc88e-4b2a-4df3-8017-1d9830b94bae)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/dfbc95a1-944b-4f7c-be97-8fac4e67b3c2)

 it always gives
"node_twin_id": 0,
and it gives 
"num_gpu": 0,

### which network/s did you face the problem on?

Main

### Relevant log output

```console
"node_twin_id": 0,
and it gives 
"num_gpu": 0,
```

**Comment by A-Harby** [comment]
Also, the endpoint `https://gridproxy.dev.grid.tf/farms?node_has_gpu=true` doesn't list any farms on devnet, while there is a farm on devnet with a GPU (Farm QualiaDev with ID 4416).

**Comment by Omarabdul3ziz** [comment]
to summarise the issue we are facing with GPUs now:
- [ ] filter `has_gpu=true` returns nodes with `num_gpu: 0`
- [ ] `/farms?node_has_gpu=true` doesn't return all farms returned in `/nodes?has_gpu=true`
- [ ] on `/nodes/<node_id>/gpu` endpoint response. `node_twin_id` field is always 0
- [ ] `num_gpu` in some nodes isn't equal to the length of the same node `/gpu` endpoint response

**Comment by Omarabdul3ziz** [comment]
## Debugging findings 
> 
> * [ ]  filter `has_gpu=true` returns nodes with `num_gpu: 0`
> * [ ]  `/farms?node_has_gpu=true` doesn't return all farms returned in `/nodes?has_gpu=true`

I couldn't find the root cause for these two issues, but I suspect that it may be because of the status filter problem we had.
the GPU indexer to filter the up nodes before calling and listing its GPUs, which could lead to wrong data. 
However, both issues are no longer present on devnet or ninja stack. 
I verified this by:
- checking all the nodes that were returned from `/nodes?has_gpu=true` to have a non-zero value on the `num_gpu` field.
- for the second issue, I created a script that loops on the response of `/nodes?has_gpu=true` and only retrieves the unique farm ids, which is the same count as farms returned by `/farms?node_has_gpu=true`. 
i will keep an eye on these issues if we face them again.




---
>
> * [ ] on /nodes/<node_id>/gpu endpoint response. node_twin_id field is always 0


this happens because the actual response from `zos.gpu.list` doesn't contain a `node_twin_id` but since we already know the twin id we call the node with, i made a small change here https://github.com/threefoldtech/tfgrid-sdk-go/pull/642 that assigns it to the response



---
>
> - [ ] `num_gpu` in some nodes isn't equal to the length of the same node `/gpu` endpoint response


i suspect that is caused by removed gpus from nodes after it is indexed for the first time on `node_gpu` table, cause it is always bigger than the actuat count. I am discussing ops to take read-only access on the database to know exactly what we have on the node_gpu table.
and still working on invalidating the old indexed GPU with each indexer round

**Comment by Omarabdul3ziz** [comment]
Update:
#642 should have fixes for both issues
>
> - [ ] on `/nodes/<node_id>/gpu` endpoint response. `node_twin_id` field is always 0
> - [ ] `num_gpu` in some nodes isn't equal to the length of the same node `/gpu` endpoint response

**Comment by Omarabdul3ziz** [comment]
for the original issue:
>
>  filter has_gpu=true returns nodes with num_gpu: 0

the issue happened again on devnet, the reason it was not reproducible is because of an outsync of the trigger, there was a missing trigger to update the num_gpu field on the cache table. this should be added on this PR https://github.com/threefoldtech/tfgrid-sdk-go/pull/726/files#diff-d19f8341d42599d5484835f1bccdf531c260171afd2f1bd0e56d7bd2d6173922

**Comment by Omarabdul3ziz** [comment]
to unblock the issues on this issue we moved the fix in a different pr from the indexer one, here https://github.com/threefoldtech/tfgrid-sdk-go/pull/870
