### ISSUE TITLE
🐞 [Bug] TFRobot: add max input validation for decimal point 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#735]
### What happened?

When decimal points exceed 4 digits, like `0.0001`, it doesn't validate the input any more.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/c6588300-5391-4c66-8c2c-34680f015d15)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
"node_groups": [
    {
      "name": "[:]",
      "nodes_count": 2,
      "free_cpu": 10,
      "free_mru": 256.00001,
      "free_ssd": 10,
      "free_hdd": 50
    },
```

**Comment by Eslam-Nawara** [comment]
the problem is `256.00001` exceeded the limit `256`, I tried 16.00001 and validation passed

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/2d39499f-2e80-4c75-81ad-78f89169fb7d)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/56297793-8830-4771-9251-a455600faf01)

**Comment by Eslam-Nawara** [comment]
Work Completed:
- added a note that to docs with the expected behavior.

**Comment by A-Harby** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/51053be6-9e3b-43d7-8270-5f048e6c6635)
