### ISSUE TITLE
proxy release workflow needs fix

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#74]
- release workflow for proxy doesn't work

**Comment by xmonader** [comment]
@alichaddad please take a look at this one, Mario is off today

**Comment by rawdaGastan** [comment]
docker build fails because proxy uses a local version of rmb-sdk

**Comment by sameh-farouk** [comment]
Update:
The build fail now because of the directory replacement instruction in go.mod file for `rmb-sdk-go` module. go can't locate the specified path `../rmb-sdk-go` in the container file system.
Also this directory can't be added/copied to container fs in the docker file unless we build from the repo's root directory and specify the path to the Dockerfile inside the proxy directory, as the first step of a docker build is to send the context directory (and sub-directories) to the docker daemon.
Suggested fix for the workflow is to set the action build context to repo's root directory and specify the path to the Dockerfile. the Dockerfile needs to be adjusted as well to include the `rmb-sdk-go` directory in the image.

**Comment by AhmedHanafy725** [comment]
@sameh-farouk we already do the same in the typescript repo to include all packages in the build time. and also I think it won't increase the image size as it's done in 2 stages

**Comment by sameh-farouk** [comment]
> @sameh-farouk we already do the same in the typescript repo to include all packages in the build time. and also I think it won't increase the image size as it's done in 2 stages

yes, and regardless the build stages, docker build context won't increase the image size as extra files in the build context that aren't used by the Dockerfile (copied/added) are simply thrown away.
