### ISSUE TITLE
🐞 [Bug] TFRobot: Can't change the flist 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#742]
### What happened?

I tried to change flist to Ubuntu 22 and it failed. I tried a few times and made sure the entry point was the same as the TS client, but I still couldn't ssh.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/9ea1ad62-49ed-48a3-9a9e-7bd0f9c386ac)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
"vms": [
    {
      "name": "examplevm13",
      "vms_count": 1,
      "node_group": "test",
      "cpu": 3,
      "mem": 0.25,
      "flist": "https://hub.grid.tf/tf-official-vms/ubuntu-22.04.flist",
      "entry_point": "/",
      "root_size": 0,
      "ssh_key": "example1",
      "ssd": [
        {
          "size": 15,
          "mount_point": "/mnt/ssd"
        }
      ],
      "env_vars": {
        "user": "user1",
        "pwd": "1234"
      }
    }
  ],
```

**Comment by AbdelrahmanElawady** [comment]
The problem turned out to be with amount of memory provided to the vm as the flist crashes with very low amount of memory. If you tried deploying the same flist with more memory it should work. This issue is flist dependent and we can't guarantee the provided memory is enough for the flist. For example 0.25GB of memory can be enough for container flists but it fails for this full-vm flist. It might work with other full-vms but again it is dependent on the flist itself and we can't guarantee the memory is enough.

The solution is to use more memory.

**Comment by A-Harby** [comment]
Verified,

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/38ec0495-d95a-4539-a1e5-bef5871ad95b)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/3c376d84-cc02-4746-9120-5baf1c716695)
