### ISSUE TITLE
🐞 [Bug]: I deployed vm and k8s from `playground` but couldn't get them using `tfcmd`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-go#877]
### What happened?

- I deployed vm from playground with name `testing291` with wireguard access.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/cb36ef07-1c2d-4375-a6bc-9ba191eb1b63)

- I tried to get this vm from tfcmd (go client), but it wasn't found.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/ca348831-f7a6-494d-8e56-c36b9c3c7926)

- tfcmd version 

![Screenshot from 2024-02-29 11-23-02](https://github.com/threefoldtech/tfgrid-sdk-go/assets/54944491/7106c774-3a17-472c-89c9-c6532c85181b)

### which network/s did you face the problem on?

Dev

### Twin ID/s

5110

### Node ID/s

153

### Farm ID/s

1

### Contract ID/s

97792

**Comment by Eslam-Nawara** [comment]
This happened because full vms are not supported in the cli, so the error message `no vm with name <name> found: could not find any contracts` is valid here.

However, you can use the cli to load micro vms, but notice the cli requires the network to have suffix `netowrk` to be able to be found using the cli

**Comment by AbdelrahmanElawady** [comment]
network suffix will be removed in #882
